name: Run The Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run server
      run: |
        docker login --username prajodhpragath --password ${{secrets.SECRET_TOKEN}} ghcr.io
        docker build -t ghcr.io/prajodh/ciphers-service:latest .
        docker push ghcr.io/prajodh/ciphers-service:latest